# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  push:
    tags:
      - 'v**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        source-url: https://nuget.pkg.github.com/theeightbot/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install MAUI Workloads
      run: dotnet workload install maui --ignore-failed-sources        

    - name: Semver Parse
      id: version
      uses: release-kit/semver@v1.0.10        
        
    - name: Build Tycho.JsonSerializer
      run: dotnet build Tycho.JsonSerializer/Tycho.JsonSerializer.csproj
    - name: Create the package
      run: dotnet pack --configuration Release /p:AssemblyVersion=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} /p:Version=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} Tycho.JsonSerializer/Tycho.JsonSerializer.csproj
    - name: Publish the package to GPR
      run: dotnet nuget push Tycho.JsonSerializer/bin/Release/*.nupkg

    - name: Build Tycho.JsonSerializer.NewtonsoftJson
      run: dotnet build Tycho.JsonSerializer.NewtonsoftJson/Tycho.JsonSerializer.NewtonsoftJson.csproj
    - name: Create the package
      run: dotnet pack --configuration Release /p:AssemblyVersion=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} /p:Version=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} Tycho.JsonSerializer.NewtonsoftJson/Tycho.JsonSerializer.NewtonsoftJson.csproj
    - name: Publish the package to GPR
      run: dotnet nuget push Tycho.JsonSerializer.NewtonsoftJson/bin/Release/*.nupkg

    - name: Build Tycho.JsonSerializer.SystemTextJson
      run: dotnet build Tycho.JsonSerializer.SystemTextJson/Tycho.JsonSerializer.SystemTextJson.csproj
    - name: Create the package
      run: dotnet pack --configuration Release /p:AssemblyVersion=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} /p:Version=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} Tycho.JsonSerializer.SystemTextJson/Tycho.JsonSerializer.SystemTextJson.csproj
    - name: Publish the package to GPR
      run: dotnet nuget push Tycho.JsonSerializer.SystemTextJson/bin/Release/*.nupkg

    - name: Build Tycho    
      run: dotnet build Tycho/Tycho.csproj
    - name: Create the package
      run: dotnet pack --configuration Release  /p:AssemblyVersion=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} /p:Version=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }} Tycho/Tycho.csproj
    - name: Publish the package to GPR
      run: dotnet nuget push Tycho/bin/Release/*.nupkg